// <auto-generated />
using System;
using API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace API.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20221006232332_AddPersonEntity")]
    partial class AddPersonEntity
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.9");

            modelBuilder.Entity("API.Models.Audit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("AuditPlanId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CommentPageId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("State")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AuditPlanId");

                    b.HasIndex("CommentPageId");

                    b.ToTable("Audits");
                });

            modelBuilder.Entity("API.Models.AuditPlan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CommentPageId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CommentPageId");

                    b.ToTable("AuditPlans");
                });

            modelBuilder.Entity("API.Models.Comment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CommentPageId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("State")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CommentPageId");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("API.Models.CommentPage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("CommentPages");
                });

            modelBuilder.Entity("API.Models.Person", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Persons");
                });

            modelBuilder.Entity("API.Models.PersonAudited", b =>
                {
                    b.Property<Guid>("AuditId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("TEXT");

                    b.HasKey("AuditId", "PersonId");

                    b.HasIndex("PersonId");

                    b.ToTable("PersonAudited");
                });

            modelBuilder.Entity("API.Models.PersonAuditor", b =>
                {
                    b.Property<Guid>("AuditId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("TEXT");

                    b.HasKey("AuditId", "PersonId");

                    b.HasIndex("PersonId");

                    b.ToTable("PersonAuditor");
                });

            modelBuilder.Entity("API.Models.Schedule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("AuditId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CommentPageId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AuditId");

                    b.HasIndex("CommentPageId");

                    b.ToTable("Schedules");
                });

            modelBuilder.Entity("API.Models.Audit", b =>
                {
                    b.HasOne("API.Models.AuditPlan", null)
                        .WithMany("Audits")
                        .HasForeignKey("AuditPlanId");

                    b.HasOne("API.Models.CommentPage", "CommentPage")
                        .WithMany()
                        .HasForeignKey("CommentPageId");

                    b.Navigation("CommentPage");
                });

            modelBuilder.Entity("API.Models.AuditPlan", b =>
                {
                    b.HasOne("API.Models.CommentPage", "CommentPage")
                        .WithMany()
                        .HasForeignKey("CommentPageId");

                    b.Navigation("CommentPage");
                });

            modelBuilder.Entity("API.Models.Comment", b =>
                {
                    b.HasOne("API.Models.CommentPage", null)
                        .WithMany("Comments")
                        .HasForeignKey("CommentPageId");
                });

            modelBuilder.Entity("API.Models.PersonAudited", b =>
                {
                    b.HasOne("API.Models.Audit", "Audit")
                        .WithMany("PersonAudited")
                        .HasForeignKey("AuditId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API.Models.Person", "Person")
                        .WithMany("PersonAudited")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Audit");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("API.Models.PersonAuditor", b =>
                {
                    b.HasOne("API.Models.Audit", "Audit")
                        .WithMany("PersonAuditors")
                        .HasForeignKey("AuditId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API.Models.Person", "Person")
                        .WithMany("PersonAuditors")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Audit");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("API.Models.Schedule", b =>
                {
                    b.HasOne("API.Models.Audit", null)
                        .WithMany("Schedules")
                        .HasForeignKey("AuditId");

                    b.HasOne("API.Models.CommentPage", "CommentPage")
                        .WithMany()
                        .HasForeignKey("CommentPageId");

                    b.Navigation("CommentPage");
                });

            modelBuilder.Entity("API.Models.Audit", b =>
                {
                    b.Navigation("PersonAudited");

                    b.Navigation("PersonAuditors");

                    b.Navigation("Schedules");
                });

            modelBuilder.Entity("API.Models.AuditPlan", b =>
                {
                    b.Navigation("Audits");
                });

            modelBuilder.Entity("API.Models.CommentPage", b =>
                {
                    b.Navigation("Comments");
                });

            modelBuilder.Entity("API.Models.Person", b =>
                {
                    b.Navigation("PersonAudited");

                    b.Navigation("PersonAuditors");
                });
#pragma warning restore 612, 618
        }
    }
}
